name:                entangled
version:             0.2.0.0
synopsis:            bi-directional tangle daemon for literate programming
description:         ! 'Makes literate programming easier. EnTangleD allows you
                     to write programs as code blocks in a markdown file. These 
                     code blocks are tangled into compilable source files 
                     whenever you write the markdown files. The other way 
                     around, if you change any of the generated source files, 
                     the markdown is updated to match the changes. This way, 
                     you can still use your editor, debugger or IDE on the 
                     generated code.'
github:              "jhidding/enTangleD"
homepage:            https://jhidding.github.io/enTangleD
license:             Apache-2.0
author:              "Johan Hidding"
maintainer:          "j.hidding@esciencecenter.nl"
copyright:           "2018-2019 Johan Hidding, Netherlands eScience Center"

extra-source-files:
- README.md
- ChangeLog.md
- scripts/tangle
- scripts/weave
- scripts/annotate-code-blocks.lua
- scripts/list.lua
- scripts/tangle.lua
- scripts/header.html
- scripts/style.css
- scripts/eisvogel.tex

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:         Please see the README on GitHub at <https://github.com/githubuser/pandoc-noweb-daemon#readme>

dependencies:
# standard libraries
- base >= 4.7 && < 5
- containers >= 0.5.9 && < 0.7
- mtl >= 2.2 && < 3
- hspec >= 2.5 && < 3
- microlens-platform >= 0.3 && < 0.4
- text >= 1.2 && < 2
- directory >= 1.3 && < 2
- filepath >= 1.4 && < 2
- random >= 1.0 && < 2
- uuid >= 1.3 && < 2
- time >= 1.8 && < 2

# functionality
- optparse-applicative >= 0.14 && < 0.15
- fsnotify >= 0.3 && < 0.4
- parsec >= 3 && < 4
- regex-tdfa >= 1.2 && < 2
- array >= 0.5 && < 1
- terminal-size >= 0.3 && < 1
- prettyprinter >= 1.2 && < 2
- prettyprinter-ansi-terminal >= 1.1 && < 2
- dhall >= 1 && < 2

# dependencies I may want to get rid of
- either >= 5 && < 6
- extra >= 1.6 && < 2

library:
  source-dirs: src
  # default-extensions:
  # - OverloadedStrings

executables:
  entangled:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - entangled

tests:
  entangled-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - entangled
